### ISSUE TITLE
Code/Scripts

### ISSUE THREAD

**Issue by Nazeeefa** [macarima/KOREF_PromethION_paper#1]
Hi, 

I have been reading your paper and I was wondering where can I find the information on how analyses were done and/or how figures were generated? Is there any code or list of tools mentioned somewhere? That would be helpful for a purpose of reproducibility or testing.

Cheers,
Nazeefa

**Comment by macarima** [comment]
> Hi,
> 
> I have been reading your paper and I was wondering where can I find the information on how analyses were done and/or how figures were generated? Is there any code or list of tools mentioned somewhere? That would be helpful for a purpose of reproducibility or testing.
> 
> Cheers,
> Nazeefa

Dear Nazeefa,

All methods including parameters are described in the paper and this github page. 
https://github.com/macarima/KOREF_PromethION_paper

The figure was made by R. We did not make any scripts for making figures.

Thank you for your attention.

With best regards,
Kim
